name: "CI for version tags"

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: m1k1o/neko

jobs:
  build-base:
    runs-on: ubuntu-latest
    #
    # do not run on forks
    #
    if: github.repository_owner == 'm1k1o'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/base
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,format=long
      - 
        name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: .docker/base/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build:
    runs-on: ubuntu-latest
    #
    # do not run on forks
    #
    if: github.repository_owner == 'm1k1o'
    needs: [ build-base ]
    strategy:
      # Will build all images even if some fail.
      matrix:
        include:
          - tag: firefox
            platforms: linux/amd64,linux/arm64
          - tag: chromium
            platforms: linux/amd64,linux/arm64
          - tag: google-chrome
            platforms: linux/amd64
          - tag: ungoogled-chromium
            platforms: linux/amd64,linux/arm64
          - tag: microsoft-edge
            platforms: linux/amd64
          - tag: brave
            platforms: linux/amd64
          - tag: vivaldi
            platforms: linux/amd64
          - tag: tor-browser
            platforms: linux/amd64,linux/arm64
          - tag: remmina
            platforms: linux/amd64
          - tag: vlc
            platforms: linux/amd64,linux/arm64
          - tag: xfce
            platforms: linux/amd64,linux/arm64
    env:
      TAG_NAME: ${{ matrix.tag }}
      PLATFORMS: ${{ matrix.platforms }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ env.TAG_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - 
        name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .docker/${{ env.TAG_NAME }}
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/base:sha-${{ github.sha }}
